// ==============================================================================
// KONARK HRMS
// Authentication Types
// ==============================================================================

export const AUTH_ROLES = [
  "ADMIN",
  "HR",
  "ACCOUNTANT",
  "MANAGER",
  "SUPERVISOR",
  "EMPLOYEE",
] as const;

export type AuthRole = (typeof AUTH_ROLES)[number];

export const AUTH_PROVIDERS = [
  "credentials",
  "google",
  "github",
] as const;

export type AuthProvider = (typeof AUTH_PROVIDERS)[number];

// ==============================================================================
// Tenant
// ==============================================================================

export interface AuthUserTenant {
  readonly id: string;
  readonly name: string;
  readonly slug: string;
}

// ==============================================================================
// User
// ==============================================================================

export interface User {
  /**
   * Unique database identifier.
   * (Future backend compatibility)
   */
  readonly id: string;

  /**
   * Login identifier used for authentication.
   */
  readonly loginId: string;

  readonly firstName: string;
  readonly lastName: string;

  /**
   * Optional convenience field.
   * Can be generated by backend or frontend.
   */
  readonly fullName?: string;

  readonly email: string;

  readonly role: AuthRole;

  // ---------------------------------------------------------------------------
  // Employee Information
  // ---------------------------------------------------------------------------

  readonly employeeId: string;
  readonly phone: string;
  readonly department: string;
  readonly designation: string;
  readonly company: string;

  readonly avatarUrl?: string;

  // ---------------------------------------------------------------------------
  // Multi Tenant
  // ---------------------------------------------------------------------------

  readonly tenant: AuthUserTenant;

  readonly isSuperAdmin: boolean;

  readonly allowedTenants?: readonly AuthUserTenant[];
}

export type AuthUser = User;

// ==============================================================================
// Session
// ==============================================================================

export interface AuthSession {
  readonly token: string;

  /**
   * Reserved for backend integration.
   */
  readonly refreshToken?: string;

  readonly user: User;

  readonly issuedAt?: string;
  readonly expiresAt?: string;

  readonly provider?: AuthProvider;
}

// ==============================================================================
// Authentication Response
// ==============================================================================

export interface AuthResponse {
  readonly success: boolean;
  readonly message: string;

  readonly user?: User;
  readonly token?: string;

  readonly session?: AuthSession;
}

// ==============================================================================
// Authentication State
// ==============================================================================

export interface AuthState {
  readonly user: User | null;

  readonly isAuthenticated: boolean;

  readonly isLoading: boolean;
}