import { LeaveRequest } from "@/types/leave";

const getOffsetDateString = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

export const mockLeaveRequests: LeaveRequest[] = [
  // ==========================================
  // COMPLETED LEAVES (PAST, APPROVED)
  // ==========================================
  {
    id: "LV-1001",
    employeeId: "emp-001",
    employeeCode: "EMP001",
    employeeName: "John Doe",
    department: "Engineering",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(-25),
    endDate: getOffsetDateString(-15),
    totalDays: 11,
    appliedOn: getOffsetDateString(-35),
    status: "APPROVED",
    reason: "Annual family vacation out of station",
  },
  {
    id: "LV-1006",
    employeeId: "emp-006",
    employeeCode: "EMP006",
    employeeName: "William Wilson",
    department: "Sales",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(-45),
    endDate: getOffsetDateString(-35),
    totalDays: 11,
    appliedOn: getOffsetDateString(-50),
    status: "APPROVED",
    reason: "Home town festival celebrations with family",
  },
  {
    id: "LV-1011",
    employeeId: "emp-011",
    employeeCode: "EMP011",
    employeeName: "Isabella Garcia",
    department: "Marketing",
    leaveType: "CASUAL_LEAVE",
    startDate: getOffsetDateString(-10),
    endDate: getOffsetDateString(-9),
    totalDays: 2,
    appliedOn: getOffsetDateString(-12),
    status: "APPROVED",
    reason: "Urgent physical property registration at municipal office",
  },
  {
    id: "LV-1014",
    employeeId: "emp-014",
    employeeCode: "EMP014",
    employeeName: "Joseph Clark",
    department: "IT",
    leaveType: "CASUAL_LEAVE",
    startDate: getOffsetDateString(-20),
    endDate: getOffsetDateString(-19),
    totalDays: 2,
    appliedOn: getOffsetDateString(-22),
    status: "APPROVED",
    reason: "Emergency domestic water pipeline damage repairs",
  },
  {
    id: "LV-1016",
    employeeId: "emp-016",
    employeeCode: "EMP016",
    employeeName: "Charles Lewis",
    department: "HR",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(-60),
    endDate: getOffsetDateString(-51),
    totalDays: 10,
    appliedOn: getOffsetDateString(-65),
    status: "APPROVED",
    reason: "Post-campaign restorative sabbatical",
  },
  {
    id: "LV-1017",
    employeeId: "emp-017",
    employeeCode: "EMP017",
    employeeName: "Mia Lee",
    department: "Finance",
    leaveType: "SICK_LEAVE",
    startDate: getOffsetDateString(-8),
    endDate: getOffsetDateString(-5),
    totalDays: 4,
    appliedOn: getOffsetDateString(-9),
    status: "APPROVED",
    reason: "Severe food poisoning treatment and observation rest",
  },

  // ==========================================
  // ACTIVE LEAVES (CURRENTLY ACTIVE, APPROVED)
  // ==========================================
  {
    id: "LV-1002",
    employeeId: "emp-002",
    employeeCode: "EMP002",
    employeeName: "Jane Smith",
    department: "HR",
    leaveType: "SICK_LEAVE",
    startDate: getOffsetDateString(-1),
    endDate: getOffsetDateString(2),
    totalDays: 4,
    appliedOn: getOffsetDateString(-5),
    status: "APPROVED",
    reason: "Recovery from inpatient surgical procedure",
  },
  {
    id: "LV-1003",
    employeeId: "emp-003",
    employeeCode: "EMP003",
    employeeName: "Robert Johnson",
    department: "Finance",
    leaveType: "CASUAL_LEAVE",
    startDate: getOffsetDateString(-2),
    endDate: getOffsetDateString(1),
    totalDays: 4,
    appliedOn: getOffsetDateString(-7),
    status: "APPROVED",
    reason: "Attending sister's marriage ceremony",
  },
  {
    id: "LV-1007",
    employeeId: "emp-007",
    employeeCode: "EMP007",
    employeeName: "Olivia Taylor",
    department: "IT",
    leaveType: "WORK_FROM_HOME",
    startDate: getOffsetDateString(-3),
    endDate: getOffsetDateString(1),
    totalDays: 5,
    appliedOn: getOffsetDateString(-6),
    status: "APPROVED",
    reason: "Residential relocation and home office setup",
  },
  {
    id: "LV-1009",
    employeeId: "emp-009",
    employeeCode: "EMP009",
    employeeName: "Sophia Martinez",
    department: "HR",
    leaveType: "MATERNITY_LEAVE",
    startDate: getOffsetDateString(-40),
    endDate: getOffsetDateString(50),
    totalDays: 91,
    appliedOn: getOffsetDateString(-50),
    status: "APPROVED",
    reason: "Standard maternity rest and childcare planning",
  },
  {
    id: "LV-1022",
    employeeId: "emp-022",
    employeeCode: "EMP022",
    employeeName: "Daniel King",
    department: "Engineering",
    leaveType: "PATERNITY_LEAVE",
    startDate: getOffsetDateString(-4),
    endDate: getOffsetDateString(6),
    totalDays: 11,
    appliedOn: getOffsetDateString(-10),
    status: "APPROVED",
    reason: "Paternity leave for newborn care and partner support",
  },

  // ==========================================
  // UPCOMING APPROVED LEAVES (FUTURE, APPROVED)
  // ==========================================
  {
    id: "LV-1012",
    employeeId: "emp-012",
    employeeCode: "EMP012",
    employeeName: "David Martin",
    department: "Operations",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(15),
    endDate: getOffsetDateString(24),
    totalDays: 10,
    appliedOn: getOffsetDateString(-1),
    status: "APPROVED",
    reason: "Planned annual summer travel with parents",
  },
  {
    id: "LV-1020",
    employeeId: "emp-020",
    employeeCode: "EMP020",
    employeeName: "Alexander Allen",
    department: "Sales",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(10),
    endDate: getOffsetDateString(19),
    totalDays: 10,
    appliedOn: getOffsetDateString(-2),
    status: "APPROVED",
    reason: "Relocation to corporate residential apartments",
  },
  {
    id: "LV-1021",
    employeeId: "emp-021",
    employeeCode: "EMP021",
    employeeName: "Grace Young",
    department: "IT",
    leaveType: "SICK_LEAVE",
    startDate: getOffsetDateString(5),
    endDate: getOffsetDateString(8),
    totalDays: 4,
    appliedOn: getOffsetDateString(-3),
    status: "APPROVED",
    reason: "Scheduled minor ophthalmic corrective procedure",
  },
  {
    id: "LV-1025",
    employeeId: "emp-025",
    employeeCode: "EMP025",
    employeeName: "Zoe Hill",
    department: "Marketing",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(30),
    endDate: getOffsetDateString(44),
    totalDays: 15,
    appliedOn: getOffsetDateString(-10),
    status: "APPROVED",
    reason: "Extended annual leave block for personal travels",
  },

  // ==========================================
  // PENDING LEAVES (FUTURE, PENDING)
  // ==========================================
  {
    id: "LV-1005",
    employeeId: "emp-005",
    employeeCode: "EMP005",
    employeeName: "Michael Brown",
    department: "Operations",
    leaveType: "SICK_LEAVE",
    startDate: getOffsetDateString(8),
    endDate: getOffsetDateString(12),
    totalDays: 5,
    appliedOn: getOffsetDateString(-2),
    status: "PENDING",
    reason: "Upcoming diagnostic medical checks and doctor observation",
  },
  {
    id: "LV-1010",
    employeeId: "emp-010",
    employeeCode: "EMP010",
    employeeName: "Benjamin Thomas",
    department: "Finance",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(45),
    endDate: getOffsetDateString(59),
    totalDays: 15,
    appliedOn: getOffsetDateString(-5),
    status: "PENDING",
    reason: "House construction and maintenance monitoring",
  },
  {
    id: "LV-1015",
    employeeId: "emp-015",
    employeeCode: "EMP015",
    employeeName: "Amelia Rodriguez",
    department: "Engineering",
    leaveType: "CASUAL_LEAVE",
    startDate: getOffsetDateString(14),
    endDate: getOffsetDateString(16),
    totalDays: 3,
    appliedOn: getOffsetDateString(-4),
    status: "PENDING",
    reason: "Family religious rituals in hometown",
  },
  {
    id: "LV-1019",
    employeeId: "emp-019",
    employeeCode: "EMP019",
    employeeName: "Evelyn Hall",
    department: "Operations",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(60),
    endDate: getOffsetDateString(74),
    totalDays: 15,
    appliedOn: getOffsetDateString(-12),
    status: "PENDING",
    reason: "House shifting and setting up primary residence",
  },
  {
    id: "LV-1023",
    employeeId: "emp-023",
    employeeCode: "EMP023",
    employeeName: "Lily Wright",
    department: "HR",
    leaveType: "WORK_FROM_HOME",
    startDate: getOffsetDateString(12),
    endDate: getOffsetDateString(13),
    totalDays: 2,
    appliedOn: getOffsetDateString(-2),
    status: "PENDING",
    reason: "Online professional certification training and exam",
  },

  // ==========================================
  // REJECTED LEAVES (FUTURE/PAST, REJECTED)
  // ==========================================
  {
    id: "LV-1004",
    employeeId: "emp-004",
    employeeCode: "EMP004",
    employeeName: "Emily Davis",
    department: "Marketing",
    leaveType: "COMP_OFF",
    startDate: getOffsetDateString(6),
    endDate: getOffsetDateString(7),
    totalDays: 2,
    appliedOn: getOffsetDateString(-1),
    status: "REJECTED",
    reason: "Comp Off request rejected due to project delivery commitments.",
  },
  {
    id: "LV-1013",
    employeeId: "emp-013",
    employeeCode: "EMP013",
    employeeName: "Charlotte Robinson",
    department: "Sales",
    leaveType: "SICK_LEAVE",
    startDate: getOffsetDateString(-5),
    endDate: getOffsetDateString(-3),
    totalDays: 3,
    appliedOn: getOffsetDateString(-7),
    status: "REJECTED",
    reason: "Severe acute migraine rest - rejected due to missing medical documents",
  },
  {
    id: "LV-1024",
    employeeId: "emp-024",
    employeeCode: "EMP024",
    employeeName: "Samuel Lopez",
    department: "Finance",
    leaveType: "EARNED_LEAVE",
    startDate: getOffsetDateString(22),
    endDate: getOffsetDateString(31),
    totalDays: 10,
    appliedOn: getOffsetDateString(-5),
    status: "REJECTED",
    reason: "Personal business travel - rejected due to critical sprint delivery commitments",
  },

  // ==========================================
  // CANCELLED LEAVES (PAST, CANCELLED)
  // ==========================================
  {
    id: "LV-1008",
    employeeId: "emp-008",
    employeeCode: "EMP008",
    employeeName: "James Anderson",
    department: "Engineering",
    leaveType: "HALF_DAY",
    startDate: getOffsetDateString(-18),
    endDate: getOffsetDateString(-18),
    totalDays: 0.5,
    appliedOn: getOffsetDateString(-19),
    status: "CANCELLED",
    reason: "Routine health consultation - cancelled as medical appointment rescheduled",
  },
  {
    id: "LV-1018",
    employeeId: "emp-018",
    employeeCode: "EMP018",
    employeeName: "Henry Walker",
    department: "Marketing",
    leaveType: "CASUAL_LEAVE",
    startDate: getOffsetDateString(-6),
    endDate: getOffsetDateString(-5),
    totalDays: 2,
    appliedOn: getOffsetDateString(-7),
    status: "CANCELLED",
    reason: "Out of station travel plans - cancelled as personal plans changed",
  }
];